name: waspha
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+20

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.8
  google_maps_flutter: ^2.4.0
  location: ^5.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  dio: ^5.3.4
  otp_text_field: ^1.1.3
  cached_network_image: ^3.2.3
  bitmap:
    git:
      url: https://github.com/bluefireteam/bitmap.git
      ref: master
  phone_form_field: ^8.1.0
  shared_preferences: ^2.2.0
  google_places_flutter:
    git:
      url: https://github.com/9init/Google-AutoComplete-TextField-Flutter.git
      ref: master
  dio_cookie_manager: ^3.1.1
  # Internationalization and localization features
  intl: ^0.18.1
  table_calendar: ^3.0.9
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  firebase_core: ^2.16.0
  path_provider: ^2.1.1
  geocoder2: ^1.4.0
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-beta.2
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  flutter_credit_card: ^4.0.1
  credit_card_type_detector: ^3.0.0
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.7+1
  app_tracking_transparency: ^2.0.4
  geolocator: ^10.1.0
  flutter_screenutil: ^5.9.0
  firebase_auth: ^4.15.0
  # Validators for form fields
  form_builder_validators: ^9.1.0
  # Form builder creation of data collection forms in Flutter by removing the boilerplate needed to build a form, validate fields, react to changes and collect final user input.
  flutter_form_builder: ^9.1.1
  flutter_datetime_picker_plus: ^2.1.0
  # A toast library for friendly user interfaces message
  fluttertoast: ^8.2.4

  # Dependency Injection service locator
  injectable: ^2.3.2

  # Dependency Injection service locator
  get_it: ^7.6.4

  # A lightweight and blazing fast key-value database for Flutter
  hive: ^2.2.3

  # Hive database support for Flutter
  hive_flutter: ^1.1.0
  # Functional error handling in flutter
  dartz: ^0.10.1

  # helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.6
  flutter_launcher_icons: ^0.13.1
  # Injectable Generator is a generator for injectable.
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.3.2
  # `dart run intl_utils:generate`
  intl_utils: ^2.8.6
  #easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views and voiding SizedBox(height and width)it handling it internally
  gap: ^3.0.1
  #A package provides an easy way to add skeleton effect
  shimmer: ^3.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.



flutter_gen:
  output: lib/core/assets_gen
  line_length: 50

  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets
  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/nearby/
  - assets/images/onboarding/
  - assets/images/credit/
  - assets/images/address/
  - assets/images/map_markers/
  - assets/images/provider_menu/
  - assets/images/app/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
          style: normal

        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
          style: normal

        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
          style: normal

        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
          style: normal
flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
  class_name: AppLocalization
  main_locale: en
  synthetic-package: false
